dist: xenial
sudo: false

language: python

cache:
  directories:
  - $HOME/.cache/pip
  - $HOME/.cache/pip
  - $HOME/download

addons:
  apt:
    packages:
      - python3-numpy
      - python3-scipy

matrix:
  include:
    - env: PYTHON_VERSION="3.8"
    - env: PYTHON_VERSION="3.9"

install:
  # install miniconda
  - deactivate
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - MINICONDA_PATH=/home/travis/miniconda
  - chmod +x miniconda.sh && ./miniconda.sh -b -p $MINICONDA_PATH
  - export PATH=$MINICONDA_PATH/bin:$PATH
  - conda update --yes conda
  # create the testing environment
  - conda create -n testenv --yes python=$PYTHON_VERSION pip
  - source activate testenv
  - pip install codecov
  - pip install .

script:
  - mkdir for_test
  - cd for_test
  - pytest -v --cov=sportsbet --pyargs sportsbet

after_success:
  - codecov